name: Run Lint and Test Charts manually

on:
  workflow_dispatch:
    inputs:
      TARGET_REPO:
        description: 'target repo'
        required: true
        default: 'https://github.com/mosip/mosip-helm'
        type: string
      TARGET_BRANCH:
        description: 'target branch'
        required: true
        default: 'gh-pages'
        type: string
      IGNORE_CHARTS:
        description: 'Ignore linting for list of charts separated by pipe(|)'
        required: true
        default: 'reporting|reporting-init|activemq-artemis'
        type: string
      LINT_ALL_CHARTS:
        description: 'Run chart linting for all charts (yes|no)'
        required: true
        default: 'no'
        type: string

jobs:
  lint-chart:
    uses: syedsalman3753/kattu/.github/workflows/helm-lint-manual.yml@master
    with:
      TARGET_REPO: ${{ inputs.TARGET_REPO }}
      TARGET_BRANCH: ${{ inputs.TARGET_BRANCH }}
      IGNORE_CHARTS: ${{ inputs.IGNORE_CHARTS }}
      LINT_ALL_CHARTS: ${{ inputs.LINT_ALL_CHARTS }}
