name: Publish mosip-helm charts

on:
  push:
    branches:
      - 1.2.0.*
      - develop
    paths:
      - 'charts/**'

jobs:
  Generate_Documentation:
    uses: syedsalman3753/kattu/.github/workflows/helm-charts-publish-to-gh-pages.yml@master
    with:
      HELM_REPO_URL: https://${{ github.actor }}.github.io/mosip-helm