name: Publish mosip-helm charts

on:
  push:
    branches:
      - 1.2.0.*
      - develop
    paths:
      - 'charts/**'

jobs:
  Generate_Documentation:
    needs: Lint
    uses: syedsalman3753/kattu/.github/workflows/publish-helm-charts.yml@master
    with:
      HELM_REPO_URL: https://${{ github.actor }}.github.io/mosip-helm