name: Publish mosip-helm charts

on:
  push:
    branches:
      - 1.2.0.*
      - develop

jobs:
  Generate_Documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: syedsalman3753/kattu/.github/actions/helm/publish-helm-charts@master